# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8279a1a1278f468713b7aaf5fad1f7dc"
name = "StayBoost"
handle = "stayboost"
application_url = "https://spider-batman-corn-anything.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://spider-batman-corn-anything.trycloudflare.com/auth/callback", "https://spider-batman-corn-anything.trycloudflare.com/auth/shopify/callback", "https://spider-batman-corn-anything.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
